In [1]:
import pandas as pd
from IPython.display import display

In [2]:
file_path = '/Users/albertomarques/Proyectos/Bootcamp/Curso2026/Semana_2/Proyecto_Semana_2/Proyecto-Shark-Attacks/DateSet_Ataque_Tiburones.xls'
shark_df = pd.read_excel('/Users/albertomarques/Proyectos/Bootcamp/Curso2026/Semana_2/Proyecto_Semana_2/Proyecto-Shark-Attacks/DateSet_Ataque_Tiburones.xls')

In [12]:
def first_visualitation(file):
    print(file.shape)
    display(file.head())
    display(file.tail())
    display(file.nunique())
    display(file.describe().T)
    display(file.describe(include = 'str').T)

In [13]:
first_visualitation(shark_df)

(7087, 23)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,14/04,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,...,Unknown,WIC News: Melissa Michaelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,...,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,...,Unknown,Melissa Michaelson: Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
7082,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
7083,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
7084,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
7085,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
7086,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

Date              6126
Year               261
Type                14
Country            253
State              948
Location          4631
Activity          1612
Name              5801
Sex                 11
Age                252
Injury            4197
Fatal Y/N           12
Time               477
Species           1746
Source            5413
pdf               6789
href formula      6784
href              6776
Case Number       6777
Case Number.1     6775
original order    6797
Unnamed: 21          1
Unnamed: 22          2
dtype: int64

,count,mean,std,min,25%,50%,75%,max
Year,7085.0,1936.170501,270.451322,0.0,1948.0,1987.0,2010.0,2026.0
original order,6799.0,3401.152081,1963.076319,2.0,1701.5,3401.0,5100.5,6802.0

,count,unique,top,freq
Type,7069,14,Unprovoked,5237
Country,7037,253,USA,2580
State,6600,948,Florida,1192
Location,6520,4631,"New Smyrna Beach, Volusia County",191
Activity,6504,1612,Surfing,1151
Name,6869,5801,male,679
Sex,6509,11,M,5682
Injury,7051,4197,FATAL,863
Species,3956,1746,White shark,194
href formula,6794,6784,http://sharkattackfile.net/spreadsheets/pdf_di...,2
href,6796,6776,http://sharkattackfile.net/spreadsheets/pdf_di...,4
Case Number,6798,6777,2021.12.06,2
Case Number.1,6797,6775,2022.03.15,2
Unnamed: 21,1,1,stopped here,1
Unnamed: 22,2,2,Teramo,1

In [37]:
columns = ['Type','Country','State','Location','Activity']
for col in columns:
    display(shark_df[col].value_counts())

Type
Unprovoked             5237
Provoked                642
Invalid                 552
Watercraft              355
Sea Disaster            242
Questionable             26
Boat                      7
 Provoked                 2
UNprovoked                1
unprovoked                1
?                         1
Unconfirmed               1
Unverified                1
Under investigation       1
Name: count, dtype: int64

Country
USA                   2580
AUSTRALIA             1482
SOUTH AFRICA           597
NEW ZEALAND            144
BAHAMAS                136
                      ...
BAHREIN                  1
KOREA                    1
RED SEA?                 1
ASIA?                    1
CEYLON (SRI LANKA)       1
Name: count, Length: 253, dtype: int64

State
Florida                              1192
New South Wales                       522
Queensland                            354
Hawaii                                345
California                            328
                                     ...
Riau Province                           1
Bikini Atoll                            1
Between New Ireland & New Britain       1
Ba Ria-Vung Tau  Province               1
Moala Island                            1
Name: count, Length: 948, dtype: int64

Location
New Smyrna Beach, Volusia County       191
Daytona Beach, Volusia County           31
Ponce Inlet, Volusia County             28
Myrtle Beach, Horry County              22
Melbourne Beach, Brevard County         20
                                      ...
                                         1
Roebuck Bay                              1
Ocracoke Inlet                           1
Panama Bay 8ºN, 79ºW                     1
Below the English fort, Trincomalee      1
Name: count, Length: 4631, dtype: int64

Activity
Surfing                                               1151
Swimming                                              1016
Fishing                                                494
Spearfishing                                           391
Wading                                                 178
                                                      ...
Swimming in pool formed by construction of a wharf       1
Swimming around anchored ship                            1
Crew swimming alongside their anchored ship              1
4 men were bathing                                       1
Wreck of  large double sailing canoe                     1
Name: count, Length: 1612, dtype: int64

In [40]:
for col in columns:
    print(f'Unique values for {col}: {shark_df[col].unique()}')

Unique values for Type: <StringArray>
[         'UNprovoked',          'Unprovoked',            'Provoked',
        'Questionable',          'unprovoked',           ' Provoked',
          'Watercraft',        'Sea Disaster',                   nan,
                   '?',         'Unconfirmed',          'Unverified',
             'Invalid', 'Under investigation',                'Boat']
Length: 15, dtype: str
Unique values for Country: <StringArray>
[                'Maldives',                'Australia',
                  'Bahamas',                      'USA',
            'New Caledonia',           'Cayman Islands',
                   'Brazil',        'US Virgin Islands',
               'Mozambique',         'French Polynesia',
 ...
        'MEDITERRANEAN SEA',                   'SWEDEN',
                   'ROATAN', 'Between PORTUGAL & INDIA',
                 'DJIBOUTI',                  'BAHREIN',
                    'KOREA',                 'RED SEA?',
                    'ASIA?',       'CEYLON (SRI LANKA)']
Length: 254, dtype: str
Unique values for State: <StringArray>
[                 'Gaafu Alif Atoll',                   'South Australia',
                     'Andros Island',                               'NSW',
                        'California',                 'Western Australia',
                        'Queensland',                            'Noumea',
              'Little Cayman Island',                            'Recife',
 ...
               'Milne Bay  Province',                   'Island of Volos',
                  'Amirante Islands',               'Kadavu Island Group',
                'Toamasina Province',                     'Riau Province',
                      'Bikini Atoll', 'Between New Ireland & New Britain',
         'Ba Ria-Vung Tau  Province',                      'Moala Island']
Length: 949, dtype: str
Unique values for Location: <StringArray>
[                                    'Kooddoo',
 'Middleton Beach Fleurieu Peninsula Adelaide',
                                 'Fresh Creek',
                  'Cape Jaffa Limestone Coast',
                         'Little Avalon Beach',
            'Big River Beach Mendocino County',
                                     'Exmouth',
                         'Lady Elliott Island',
                 'Anse Vata near Point Magnin',
                               'Caribbean Sea',
 ...
                                 'Symi Island',
              'Spectacle Island, Port Jackson',
                                     'Durban ',
                                    'Vũng Tàu',
     'Somewhere between Hatteras and Beaufort',
                                '            ',
                                 'Roebuck Bay',
                              'Ocracoke Inlet',
                        'Panama Bay 8ºN, 79ºW',
         'Below the English fort, Trincomalee']
Length: 4632, dtype: str
Unique values for Activity: <StringArray>
[                                                          'Swimming',
                                                            'Surfing',
                                                             'Diving',
                                                      'Wing Foiling ',
                                                         'Snorkeling',
                                                  'Jumping off rocks',
                                                       'Scuba Diving',
                                                         'Not stated',
                                                       'SCUBA Diving',
                                              'Freeing trapped shark',
 ...
 'Standing, washing rear wheels of his ambulance in ankle-deep water',
                      'Carrying a supposedly dead shark by its mouth',
                                             'Spent 8 days in dinghy',
                       'Aircraft ditched in the sea, swimming ashore',
                                                'Wooden fishing boat',
                 'Swimming in pool formed by construction of a wharf',
                                      'Swimming around anchored ship',
                        'Crew swimming alongside their anchored ship',
                                                 '4 men were bathing',
                               'Wreck of  large double sailing canoe']
Length: 1613, dtype: str

In [44]:
shark_df.isna().sum()

Date                 0
Year                 2
Type                18
Country             50
State              487
Location           567
Activity           583
Name               218
Sex                578
Age               2994
Injury              36
Fatal Y/N          561
Time              3527
Species           3131
Source              20
pdf                288
href formula       293
href               291
Case Number        289
Case Number.1      290
original order     288
Unnamed: 21       7086
Unnamed: 22       7085
dtype: int64

In [45]:
shark_df.duplicated().sum()

np.int64(0)